[workspace]
resolver = "2"
members = [
    "crates/eventwork",
    "crates/eventwork_websockets",
    "crates/eventwork_common",
    "crates/eventwork_memory",
]

exclude = [
    "crates/eventwork_websockets/examples",
    "crates/eventwork_websockets/src/wasm_client_example",
    "crates/eventwork/examples"
    ]

[workspace.dependencies]
bevy = { version = "0.16", default-features = false, features = ["multi_threaded", "bevy_log"] }
bincode = "1.3.3"

# Fast-compile config
[profile.dev]
opt-level = 0
overflow-checks = true
debug-assertions = true
debug = true
codegen-units = 16
lto = false
incremental = true

# Use opt level 3 for dependencies
[profile.dev.package."*"]
opt-level = 3