[workspace]
resolver = "2"
members = [
    "crates/eventwork",
    "crates/eventwork_websockets",
    "crates/eventwork_common",
]

exclude = [
    "crates/eventwork_websockets/examples",
    "crates/eventwork_websockets/src/wasm_client_example",
    "crates/eventwork/examples"
    ]

[workspace.dependencies]
bevy = { version = "0.14.0",  default-features = false }
bevy_app = {version = "0.14.0"}
bevy_ecs = {version = "0.14.0"}