[package]
name = "demo_types"
version = "0.1.0"
edition = "2021"

[features]
server = ["dep:bevy"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bevy = { version = "0.17", default-features = false, features = ["multi_threaded", "bevy_log"], optional = true }

